#!/usr/bin/env pipenv run python
import sys
import time
import re
import hashlib
import urllib.parse
import bencode

import config
import cli
from tracker import Tracker
from manager import Manager

def torrent(path):
    regex = re.compile('.+.torrent$')
    if not regex.match(path):
        print('Not a .torrent file')
        sys.exit()
    with open(path, 'rb') as stream:
        data = bencode.bdecode(bytes(stream.read()))
        info_dict = data['info']
        return info_dict['name'], data['announce'], info_dict, hashlib.sha1(bencode.bencode(info_dict)).digest()

def magnet(url):
    regex = re.compile('magnet:.+$')
    if not regex.match(url):
        print('Not a magnet link')
        sys.exit()
    params = urllib.parse.parse_qs(url[8:])
    if not all(key in params for key in ['xt', 'tr', 'dn']):
        print('Invalid magnet link')
        sys.exit()
    return params['dn'][0], params['tr'][0], None, bytes(bytearray.fromhex(params['xt'][0][9:]))

if __name__ == '__main__':
    arg = cli.Parser(sys.argv).parse()
    config.spinner = cli.Spinner()

    name, tracker_url, info, info_hash = torrent(arg) if config.COMMAND == 'torrent' else magnet(arg)

    print('\033[1m{}\033[0m'.format(name))
    config.START_TIME = time.time()

    config.tracker = Tracker(info_hash)
    config.tracker.announce(tracker_url)
    config.manager = Manager()
    if config.COMMAND == 'torrent':
        config.manager.info(info)
    config.manager.start()
